const commonAncestry = ["Cooperative Nature", "Haughty Obstinacy"];
const commonGeneral = ["Toughness", "Fleet"];
const commonSkills = ["acrobatics", "athletics", "crafting", "diplomacy", "medicine", "nature", "religion", "society"];
const commonSkillFeats = ["Cat Fall", "Forager", "Acrobatic Performer", "Group Impression", "Quick Jump"];
const deepAncestry = [
  "Cooperative Nature",
  "Haughty Obstinacy",
  "Clever Improviser",
  "Sense Allies",
  "Cooperative Soul",
];
const deepGeneral = ["Toughness", "Fleet", "Incredible Initiative", "Diehard", "Fast Recovery"];
const deepSkillFeats = [
  "Cat Fall",
  "Forager",
  "Acrobatic Performer",
  "Group Impression",
  "Quick Jump",
  "Experienced Smuggler",
  "Battle Medicine",
  "Bon Mot",
  "Quick Repair",
  "Recognize Spell",
  "Intimidating Glare",
  "Titan Wrestler",
  "Continual Recovery",
  "Ward Medic",
];
const deepArcaneSpells = [
  "Detect Magic",
  "Electric Arc",
  "Figment",
  "Frostbite",
  "Ignition",
  "Light",
  "Message",
  "Read Aura",
  "Shield",
  "Telekinetic Hand",
  "Fear",
  "Force Barrage",
  "Mystic Armor",
  "Sure Strike",
  "Dispel Magic",
  "Invisibility",
  "Laughing Fit",
  "Fireball",
  "Haste",
  "Slow",
  "Fly",
  "Translocate",
  "Wall of Fire",
  "Howling Blizzard",
  "Telepathic Bond",
];
const deepOccultSpells = [
  "Daze",
  "Detect Magic",
  "Figment",
  "Guidance",
  "Light",
  "Message",
  "Read Aura",
  "Shield",
  "Telekinetic Hand",
  "Bless",
  "Fear",
  "Phantom Pain",
  "Soothe",
  "Command",
  "Dispel Magic",
  "Invisibility",
  "Laughing Fit",
  "Heroism",
  "Haste",
  "Slow",
  "Confusion",
  "Fly",
  "Synesthesia",
  "Telepathic Bond",
];

export const expectedPf2eClassSlugs = [
  "alchemist",
  "animist",
  "barbarian",
  "bard",
  "champion",
  "cleric",
  "commander",
  "druid",
  "exemplar",
  "fighter",
  "guardian",
  "gunslinger",
  "inventor",
  "investigator",
  "kineticist",
  "magus",
  "monk",
  "oracle",
  "psychic",
  "ranger",
  "rogue",
  "sorcerer",
  "summoner",
  "swashbuckler",
  "thaumaturge",
  "witch",
  "wizard",
];

function classCase({
  applyTimeoutMs,
  className,
  classSlug,
  keyAbility,
  expectedStepIds = [],
  expectedSpellChoiceCounts,
  preferredSelections = {},
  preferredSkills = commonSkills,
  deityName,
  spellChoiceMode,
}) {
  return {
    id: `${classSlug}-l1-l5-apply-rerun`,
    label: `${className} level 1 through 5 apply/rerun`,
    ...(applyTimeoutMs === undefined ? {} : { applyTimeoutMs }),
    className,
    classSlug,
    deityName,
    keyAbility,
    targetLevel: 5,
    spellChoiceMode,
    expectedStepIds,
    expectedSpellChoiceCounts,
    preferredSelections: {
      "ancestry-feat": commonAncestry,
      "general-feat": commonGeneral,
      "skill-feat": commonSkillFeats,
      ...preferredSelections,
    },
    preferredSkills,
  };
}

function depthCase({
  id,
  label,
  targetLevel,
  expectedPickerOptions,
  expectedSkillIncreaseSelections,
  expectedSkillRanks,
  expectedStepIds = [],
  ...baseOptions
}) {
  const base = classCase({ ...baseOptions, expectedStepIds: [] });
  const boostLevels = [10, 15, 20].filter((level) => level <= targetLevel);
  const skillIncreaseLevels = [3, 5, 7, 9, 11, 13, 15, 17, 19].filter((level) => level <= targetLevel);
  const boostStepIds = boostLevels.map((level) => `ability-boosts-level-${level}`);
  const skillIncreaseStepIds = skillIncreaseLevels.map((level) => `skill-increase-level-${level}`);
  const storedBoostLevels = [1, 5, ...boostLevels];

  return {
    ...base,
    id,
    label,
    targetLevel,
    applyTimeoutMs: targetLevel >= 20 ? 120_000 : 90_000,
    expectedStepIds: [...new Set([...expectedStepIds, ...boostStepIds, ...skillIncreaseStepIds])],
    expectedBoostSteps: Object.fromEntries(
      boostStepIds.map((slotId, index) => [
        slotId,
        {
          batchLevel: boostLevels[index],
          requiredCount: 4,
          grantCount: 4,
          selectedCount: 4,
        },
      ]),
    ),
    expectedBoostBatchCounts: Object.fromEntries(storedBoostLevels.map((level) => [level, 4])),
    expectedPickerOptions,
    expectedSkillIncreaseSelections,
    expectedSkillRanks,
  };
}

export const smokeCases = [
  classCase({
    className: "Alchemist",
    classSlug: "alchemist",
    keyAbility: "int",
    expectedStepIds: ["class-branch-research-field-level-1"],
    preferredSelections: {
      "class-branch-research-field-level-1": ["Bomber", "Chirurgeon"],
      "class-feat": ["Quick Bomber", "Far Lobber"],
    },
    preferredSkills: ["crafting", "medicine", "nature", "society", "arcana", "thievery"],
  }),
  classCase({
    className: "Animist",
    classSlug: "animist",
    keyAbility: "wis",
    expectedStepIds: [
      "class-branch-animistic-practice-level-1",
      "spell-choice-animist-cantrips-level-1",
      "spell-choice-animist-rank-1-level-1",
    ],
    preferredSelections: {
      "class-branch-animistic-practice-level-1": ["Medium", "Seer"],
      "class-feat": ["Grudge Strike", "Restorative Familiar"],
    },
    preferredSkills: ["religion", "nature", "occultism", "medicine", "society"],
  }),
  classCase({
    className: "Barbarian",
    classSlug: "barbarian",
    keyAbility: "str",
    expectedStepIds: ["class-branch-instinct-level-1"],
    preferredSelections: {
      "class-branch-instinct-level-1": ["Fury Instinct", "Animal Instinct"],
      "class-feat": ["Sudden Charge", "Raging Intimidation"],
    },
    preferredSkills: ["athletics", "intimidation", "survival", "acrobatics", "nature"],
  }),
  classCase({
    className: "Bard",
    classSlug: "bard",
    keyAbility: "cha",
    expectedStepIds: [
      "class-branch-muses-level-1",
      "spell-choice-bard-cantrips-level-1",
      "spell-choice-bard-repertoire-rank-1-level-1",
      "spell-choice-bard-repertoire-rank-1-level-2",
      "spell-choice-bard-repertoire-rank-2-level-3",
      "spell-choice-bard-repertoire-rank-2-level-4",
      "spell-choice-bard-repertoire-rank-3-level-5",
    ],
    preferredSelections: {
      "class-branch-muses-level-1": ["Maestro", "Enigma"],
      "class-feat": ["Reach Spell", "Cantrip Expansion", "Bardic Lore", "Hymn of Healing"],
    },
    preferredSkills: ["occultism", "performance", "diplomacy", "deception", "society", "acrobatics"],
  }),
  {
    ...classCase({
      className: "Bard",
      classSlug: "bard",
      keyAbility: "cha",
      expectedStepIds: [
        "class-branch-muses-level-1",
        "flag-choice-none-feat-multifarious-muse-muse-level-2",
        "grant-choice-none-feat-multifarious-muse-feat-level-2",
        "spell-choice-bard-cantrips-level-1",
        "spell-choice-bard-repertoire-rank-1-level-1",
        "spell-choice-bard-repertoire-rank-1-level-2",
        "spell-choice-bard-repertoire-rank-2-level-3",
        "spell-choice-bard-repertoire-rank-2-level-4",
        "spell-choice-bard-repertoire-rank-3-level-5",
      ],
      preferredSelections: {
        "class-branch-muses-level-1": ["Maestro"],
        "class-feat-level-2": ["Multifarious Muse"],
        "class-feat-level-4": ["Cantrip Expansion", "Reach Spell"],
        "flag-choice-none-feat-multifarious-muse-muse-level-2": ["Enigma", "Polymath"],
        "grant-choice-none-feat-multifarious-muse-feat-level-2": ["Bardic Lore", "Hymn of Healing"],
        "class-feat": ["Cantrip Expansion", "Reach Spell", "Hymn of Healing"],
      },
      preferredSkills: ["occultism", "performance", "diplomacy", "deception", "society", "acrobatics"],
    }),
    id: "bard-multifarious-muse-l1-l5-apply-rerun",
    label: "Bard with Multifarious Muse flag choice level 1 through 5 apply/rerun",
  },
  classCase({
    className: "Champion",
    classSlug: "champion",
    deityName: "Sarenrae",
    keyAbility: "str",
    spellChoiceMode: "pf2e-granted",
    expectedStepIds: [
      "class-choice-deity-champion-sanctification-level-1",
      "class-branch-cause-level-1",
      "class-branch-blessing-of-the-devoted-level-3",
    ],
    preferredSelections: {
      deity: ["Sarenrae", "Pharasma", "Abadar"],
      "class-branch-cause-level-1": ["Justice", "Liberation"],
      "class-branch-blessing-of-the-devoted-level-3": ["Blessed Armament", "Blessed Shield"],
      "class-feat": ["Deity's Domain", "Ranged Reprisal"],
    },
    preferredSkills: ["religion", "athletics", "diplomacy", "medicine", "society"],
  }),
  classCase({
    className: "Cleric",
    classSlug: "cleric",
    deityName: "Sarenrae",
    keyAbility: "wis",
    expectedStepIds: [
      "class-archetype-doctrine-level-1",
      "class-choice-divine-font-divineFont-level-1",
      "class-choice-deity-cleric-sanctification-level-1",
      "class-branch-doctrine-level-1",
      "spell-choice-cleric-cantrips-level-1",
      "spell-choice-cleric-rank-1-level-1",
    ],
    preferredSelections: {
      deity: ["Sarenrae", "Pharasma", "Abadar"],
      "class-archetype-doctrine-level-1": ["Standard class path"],
      "class-branch-doctrine-level-1": ["Cloistered Cleric", "Warpriest"],
      "class-feat": ["Healing Hands", "Reach Spell", "Sap Life"],
      "skill-feat": ["Forager", "Recognize Spell", "Cat Fall", "Acrobatic Performer"],
    },
    preferredSkills: ["religion", "medicine", "diplomacy", "nature", "society", "athletics", "survival"],
  }),
  {
    ...classCase({
      className: "Cleric",
      classSlug: "cleric",
      deityName: "Sarenrae",
      keyAbility: "wis",
      expectedStepIds: [
        "class-archetype-doctrine-level-1",
        "class-choice-deity-cleric-sanctification-level-1",
        "class-feat-level-4",
        "spell-choice-cleric-cantrips-level-1",
        "spell-choice-cleric-rank-1-level-1",
      ],
      preferredSelections: {
        deity: ["Sarenrae", "Pharasma", "Abadar"],
        "class-archetype-doctrine-level-1": ["Battle Creed"],
        "class-feat": ["Healing Hands", "Reach Spell", "Sap Life"],
        "skill-feat": ["Forager", "Recognize Spell", "Cat Fall", "Acrobatic Performer"],
      },
      preferredSkills: ["religion", "medicine", "diplomacy", "nature", "society", "athletics", "survival"],
    }),
    id: "cleric-battle-creed-l1-l5-apply-rerun",
    label: "Cleric Battle Creed level 1 through 5 apply/rerun",
    forbiddenStepIds: [
      "class-choice-divine-font-divineFont-level-1",
      "class-branch-doctrine-level-1",
      "class-feat-level-2",
    ],
    expectedItemNames: [
      "Battle Creed",
      "Battle Harbinger Dedication",
      "Battle Font",
      "Bane",
      "Bless",
      "Divine Prepared Spells",
      "Toughness",
      "Fleet",
    ],
    forbiddenItemNames: ["Cloistered Cleric", "Warpriest", "Divine Font (Healing)"],
    expectedSpellcastingEntries: {
      "cleric-divine-prepared": {
        slots: {
          slot0: 5,
          slot1: 0,
          slot2: 2,
          slot3: 2,
        },
      },
      "cleric-battle-font": {
        proficiencySlug: "cleric",
        slots: {
          slot1: 0,
          slot2: 0,
          slot3: 5,
        },
      },
    },
    expectedItemDestinations: {
      Bane: "cleric-battle-font",
      Bless: "cleric-battle-font",
    },
  },
  {
    ...classCase({
      className: "Cleric",
      classSlug: "cleric",
      deityName: "Sarenrae",
      keyAbility: "wis",
      expectedStepIds: [
        "class-archetype-doctrine-level-1",
        "class-choice-deity-cleric-sanctification-level-1",
        "skill-training-cleric-level-1",
        "class-feat-level-4",
      ],
      preferredSelections: {
        deity: ["Sarenrae", "Pharasma", "Abadar"],
        "class-archetype-doctrine-level-1": ["Battle Creed"],
        "class-feat": ["Healing Hands", "Reach Spell", "Sap Life"],
        "skill-feat": ["Forager", "Recognize Spell", "Cat Fall", "Acrobatic Performer"],
      },
      preferredSkills: ["religion", "medicine", "diplomacy", "nature", "society", "survival"],
    }),
    id: "cleric-battle-creed-skill-fallback-l1-l5-apply-rerun",
    label: "Cleric Battle Creed with both dedication skills trained level 1 through 5 apply/rerun",
    preseedSkillRanks: { acrobatics: 1, athletics: 1 },
    preferredRuleChoices: { skill: "society" },
    expectedSkillRanks: { acrobatics: 1, athletics: 1, society: 1 },
    expectedItemRuleSelections: { "Battle Harbinger Dedication": { skill: "society" } },
    expectedItemNames: ["Battle Creed", "Battle Harbinger Dedication", "Battle Font", "Toughness"],
    forbiddenStepIds: [
      "class-choice-divine-font-divineFont-level-1",
      "class-branch-doctrine-level-1",
      "class-feat-level-2",
    ],
    forbiddenItemNames: ["Cloistered Cleric", "Warpriest", "Divine Font (Healing)"],
  },
  {
    ...classCase({
      className: "Cleric",
      classSlug: "cleric",
      deityName: "Sarenrae",
      keyAbility: "wis",
      expectedStepIds: [
        "class-archetype-doctrine-level-1",
        "class-archetype-battle-harbinger-toughness-replacement-level-2",
        "class-choice-deity-cleric-sanctification-level-1",
        "class-feat-level-4",
        "spell-choice-cleric-cantrips-level-1",
        "spell-choice-cleric-rank-1-level-1",
      ],
      preferredSelections: {
        deity: ["Sarenrae", "Pharasma", "Abadar"],
        "class-archetype-doctrine-level-1": ["Battle Creed"],
        "class-archetype-battle-harbinger-toughness-replacement-level-2": ["Fleet"],
        "general-feat": ["Incredible Initiative", "Diehard"],
        "class-feat": ["Healing Hands", "Reach Spell", "Sap Life"],
        "skill-feat": ["Forager", "Recognize Spell", "Cat Fall", "Acrobatic Performer"],
      },
      preferredSkills: ["religion", "medicine", "diplomacy", "nature", "society", "athletics", "survival"],
    }),
    id: "cleric-battle-creed-toughness-fallback-l1-l5-apply-rerun",
    label: "Cleric Battle Creed Toughness fallback level 1 through 5 apply/rerun",
    preseedItemUuids: ["Compendium.pf2e.feats-srd.Item.AmP0qu7c5dlBSath"],
    forbiddenStepIds: [
      "class-choice-divine-font-divineFont-level-1",
      "class-branch-doctrine-level-1",
      "class-feat-level-2",
    ],
    expectedItemNames: [
      "Battle Creed",
      "Battle Harbinger Dedication",
      "Battle Font",
      "Bane",
      "Bless",
      "Divine Prepared Spells",
      "Toughness",
      "Fleet",
    ],
    expectedItemNameCounts: { Toughness: 1 },
    forbiddenItemNames: ["Cloistered Cleric", "Warpriest", "Divine Font (Healing)"],
    expectedGrantReplacements: [
      {
        sourceItemName: "Battle Harbinger Dedication",
        flag: "toughnessFallback",
        originalUuids: [
          "Compendium.pf2e.feats-srd.Item.AmP0qu7c5dlBSath",
          "Compendium.pf2e.feats-srd.Item.Toughness",
        ],
      },
    ],
    expectedSpellcastingEntries: {
      "cleric-divine-prepared": {
        slots: { slot0: 5, slot1: 0, slot2: 2, slot3: 2 },
      },
      "cleric-battle-font": {
        proficiencySlug: "cleric",
        slots: { slot1: 0, slot2: 0, slot3: 5 },
      },
    },
    expectedItemDestinations: {
      Bane: "cleric-battle-font",
      Bless: "cleric-battle-font",
    },
  },
  {
    ...classCase({
      className: "Cleric",
      classSlug: "cleric",
      deityName: "Sarenrae",
      keyAbility: "wis",
      expectedStepIds: [
        "class-archetype-doctrine-level-1",
        "class-archetype-battle-harbinger-toughness-replacement-level-2",
        "class-choice-deity-cleric-sanctification-level-1",
        "class-feat-level-4",
        "spell-choice-cleric-cantrips-level-1",
        "spell-choice-cleric-rank-1-level-1",
      ],
      preferredSelections: {
        deity: ["Sarenrae", "Pharasma", "Abadar"],
        "class-archetype-doctrine-level-1": ["Battle Creed"],
        "class-archetype-battle-harbinger-toughness-replacement-level-2": ["Fleet"],
        "general-feat": ["Incredible Initiative", "Diehard"],
        "class-feat": ["Healing Hands", "Reach Spell", "Sap Life"],
        "skill-feat": ["Forager", "Recognize Spell", "Cat Fall", "Acrobatic Performer"],
      },
      preferredSkills: ["religion", "medicine", "diplomacy", "nature", "society", "athletics", "survival"],
    }),
    id: "cleric-battle-creed-shielded-fortune-l1-l5-apply-rerun",
    label: "Cleric Battle Creed with Shielded Fortune level 1 through 5 apply/rerun",
    backgroundName: "Shielded Fortune",
    backgroundBoosts: { "0": "con", "1": "wis" },
    forbiddenStepIds: [
      "class-choice-divine-font-divineFont-level-1",
      "class-branch-doctrine-level-1",
      "class-feat-level-2",
    ],
    expectedItemNames: [
      "Shielded Fortune",
      "Battle Creed",
      "Battle Harbinger Dedication",
      "Battle Font",
      "Bane",
      "Bless",
      "Divine Prepared Spells",
      "Toughness",
      "Fleet",
    ],
    expectedItemNameCounts: { Toughness: 1 },
    forbiddenItemNames: ["Cloistered Cleric", "Warpriest", "Divine Font (Healing)"],
    expectedGrantReplacements: [
      {
        sourceItemName: "Battle Harbinger Dedication",
        flag: "toughnessFallback",
        originalUuids: [
          "Compendium.pf2e.feats-srd.Item.AmP0qu7c5dlBSath",
          "Compendium.pf2e.feats-srd.Item.Toughness",
        ],
      },
    ],
    expectedSpellcastingEntries: {
      "cleric-divine-prepared": {
        slots: { slot0: 5, slot1: 0, slot2: 2, slot3: 2 },
      },
      "cleric-battle-font": {
        proficiencySlug: "cleric",
        slots: { slot1: 0, slot2: 0, slot3: 5 },
      },
    },
    expectedItemDestinations: {
      Bane: "cleric-battle-font",
      Bless: "cleric-battle-font",
    },
  },
  classCase({
    className: "Commander",
    classSlug: "commander",
    keyAbility: "str",
    expectedStepIds: [
      "class-branch-tactics-firstTactic-level-1",
      "class-branch-tactics-secondTactic-level-1",
      "class-branch-tactics-thirdTactic-level-1",
      "class-branch-tactics-fourthTactic-level-1",
      "class-branch-tactics-fifthTactic-level-1",
    ],
    preferredSelections: {
      "class-branch-tactics-firstTactic-level-1": ["Coordinating Maneuvers"],
      "class-branch-tactics-secondTactic-level-1": ["Defensive Retreat"],
      "class-branch-tactics-thirdTactic-level-1": ["Double Team"],
      "class-branch-tactics-fourthTactic-level-1": ["End It!"],
      "class-branch-tactics-fifthTactic-level-1": ["Gather to Me!"],
      "class-feat": ["Combat Assessment", "Defensive Advance"],
    },
    preferredSkills: ["warfare-lore", "athletics", "diplomacy", "intimidation", "society", "survival"],
    expectedItemNames: [
      "Tactics",
      "Coordinating Maneuvers",
      "Defensive Retreat",
      "Double Team",
      "End It!",
      "Gather to Me!",
    ],
    expectedItemRuleSelections: {
      Tactics: {
        firstTactic: "Compendium.pf2e.actionspf2e.Item.Kp325Qf0qpF6RCDE",
        secondTactic: "Compendium.pf2e.actionspf2e.Item.UJi0VYnhVSdnl9II",
        thirdTactic: "Compendium.pf2e.actionspf2e.Item.c5jVVnNYlP5HB6Ob",
        fourthTactic: "Compendium.pf2e.actionspf2e.Item.lI4JCQcqvrZE2U5n",
        fifthTactic: "Compendium.pf2e.actionspf2e.Item.URxnrN8ji84AoVup",
      },
    },
  }),
  classCase({
    className: "Druid",
    classSlug: "druid",
    keyAbility: "wis",
    expectedStepIds: [
      "class-choice-voice-of-nature-feat-level-1",
      "class-branch-druidic-order-level-1",
      "spell-choice-druid-cantrips-level-1",
      "spell-choice-druid-rank-1-level-1",
    ],
    preferredSelections: {
      "class-branch-druidic-order-level-1": ["Storm Order", "Leaf Order"],
      "grant-choice-none-feat-order-explorer-order-level-2": ["Leaf Order"],
      "class-feat": ["Order Explorer", "Reach Spell"],
    },
    preferredSkills: ["nature", "survival", "medicine", "athletics", "diplomacy"],
  }),
  classCase({
    className: "Exemplar",
    classSlug: "exemplar",
    keyAbility: "str",
    expectedStepIds: [
      "class-branch-divine-spark-and-ikons-firstIkon-level-1",
      "class-branch-divine-spark-and-ikons-secondIkon-level-1",
      "class-branch-divine-spark-and-ikons-thirdIkon-level-1",
      "class-branch-root-epithet-level-3",
    ],
    preferredSelections: {
      "class-branch-divine-spark-and-ikons-firstIkon-level-1": ["Eye-Catching Spot", "Gaze Sharp as Steel"],
      "class-branch-divine-spark-and-ikons-secondIkon-level-1": ["Scar of the Survivor", "Shadow Sheath"],
      "class-branch-divine-spark-and-ikons-thirdIkon-level-1": ["Skin Hard as Horn", "Gaze Sharp as Steel"],
      "class-branch-root-epithet-level-3": ["The Brave", "The Cunning"],
      "class-feat": ["Claim Initiate Domain", "Reactive Strike"],
    },
    preferredSkills: ["athletics", "diplomacy", "intimidation", "society", "acrobatics"],
  }),
  classCase({
    className: "Fighter",
    classSlug: "fighter",
    keyAbility: "str",
    expectedStepIds: ["class-choice-fighter-weapon-mastery-fighterWeaponMastery-level-5"],
    preferredSelections: {
      "class-feat": ["Reactive Shield", "Intimidating Strike", "Quick Reversal"],
      "skill-feat": ["Cat Fall", "Forager", "Acrobatic Performer", "Group Impression", "Quick Jump"],
    },
    preferredSkills: ["athletics", "acrobatics", "survival", "intimidation", "religion", "stealth"],
  }),
  {
    ...classCase({
      className: "Fighter",
      classSlug: "fighter",
      keyAbility: "str",
      expectedStepIds: [
        "class-choice-fighter-weapon-mastery-fighterWeaponMastery-level-5",
        "singleton-choice-feat-samsaran-weapon-memory-weaponOne-level-1",
        "singleton-choice-feat-samsaran-weapon-memory-weaponTwo-level-1",
      ],
      preferredSelections: {
        "ancestry-feat": ["Samsaran Weapon Memory"],
        "singleton-choice-feat-samsaran-weapon-memory-weaponOne-level-1": ["Longsword", "Falchion", "Glaive"],
        "singleton-choice-feat-samsaran-weapon-memory-weaponTwo-level-1": ["Longbow", "Composite Longbow", "Shortbow"],
        "class-feat": ["Reactive Shield", "Intimidating Strike", "Quick Reversal"],
      },
      preferredSkills: ["athletics", "acrobatics", "survival", "intimidation", "religion", "stealth"],
    }),
    id: "fighter-samsaran-weapon-memory-l1-l5-apply-rerun",
    label: "Fighter with Samsaran Weapon Memory config-feat level 1 through 5 apply/rerun",
    ancestryName: "Samsaran",
    heritageName: "Oracular Samsaran",
    ancestryBoosts: { "0": "con", "1": "wis", "2": "str" },
  },
  classCase({
    className: "Guardian",
    classSlug: "guardian",
    keyAbility: "str",
    preferredSelections: {
      "class-feat": ["Intercept Foe", "Armored Counterattack"],
    },
    preferredSkills: ["athletics", "intimidation", "medicine", "society", "survival"],
  }),
  classCase({
    className: "Gunslinger",
    classSlug: "gunslinger",
    keyAbility: "dex",
    expectedStepIds: ["class-archetype-gunslingers-way-level-1", "class-branch-gunslingers-way-level-1"],
    preferredSelections: {
      "class-archetype-gunslingers-way-level-1": ["Standard class path"],
      "class-branch-gunslingers-way-level-1": ["Way of the Pistolero", "Way of the Sniper"],
      "class-feat": ["Cover Fire", "Hit the Dirt!"],
    },
    preferredSkills: ["acrobatics", "crafting", "deception", "intimidation", "stealth", "survival"],
  }),
  {
    ...classCase({
      className: "Gunslinger",
      classSlug: "gunslinger",
      keyAbility: "dex",
      expectedStepIds: [
        "class-archetype-gunslingers-way-level-1",
        "skill-training-gunslinger-level-1",
        "spell-choice-spellshot-spellbook-cantrips-level-2",
        "class-feat-level-4",
      ],
      preferredSelections: {
        "class-archetype-gunslingers-way-level-1": ["Way of the Spellshot"],
        "spell-choice-spellshot-spellbook-cantrips-level-2": ["Detect Magic", "Ignition", "Light", "Shield"],
        "class-feat": ["Cover Fire", "Hit the Dirt!"],
      },
      preferredSkills: ["arcana", "society", "crafting", "acrobatics", "stealth", "survival"],
    }),
    id: "gunslinger-spellshot-l1-l5-apply-rerun",
    label: "Gunslinger Way of the Spellshot level 1 through 5 apply/rerun",
    forbiddenStepIds: ["class-branch-gunslingers-way-level-1", "class-feat-level-2"],
    expectedItemNames: [
      "Way of the Spellshot",
      "Thoughtful Reload",
      "Energy Shot",
      "Spellshot Dedication",
      "Spellshot Spellbook",
      "Detect Magic",
      "Ignition",
      "Light",
      "Shield",
    ],
    expectedSkillRanks: { arcana: 2, society: 2 },
    expectedItemLocations: { "Spellshot Dedication": "class-2" },
    forbiddenItemNames: ["Way of the Pistolero", "Way of the Sniper"],
    expectedSpellcastingEntries: {
      "spellshot-arcane-spellbook": {
        ability: "int",
        prepared: "prepared",
        tradition: "arcane",
        slots: { slot0: 2 },
        preparedSlots: { slot0: [null, null] },
      },
    },
    expectedItemDestinations: {
      "Detect Magic": "spellshot-arcane-spellbook",
      Ignition: "spellshot-arcane-spellbook",
      Light: "spellshot-arcane-spellbook",
      Shield: "spellshot-arcane-spellbook",
    },
  },
  classCase({
    className: "Inventor",
    classSlug: "inventor",
    keyAbility: "int",
    expectedStepIds: ["class-choice-armor-innovation-armorInnovation-level-1", "class-branch-innovation-level-1"],
    preferredSelections: {
      "class-branch-innovation-level-1": ["Armor Innovation", "Weapon Innovation"],
      "class-feat": ["Built-In Tools", "Haphazard Repair"],
    },
    preferredSkills: ["crafting", "arcana", "athletics", "society", "thievery"],
  }),
  classCase({
    className: "Investigator",
    classSlug: "investigator",
    keyAbility: "int",
    expectedStepIds: ["class-archetype-methodology-level-1", "class-branch-methodology-level-1"],
    preferredSelections: {
      "class-archetype-methodology-level-1": ["Standard class path"],
      "class-branch-methodology-level-1": [
        "Interrogation Methodology",
        "Forensic Medicine Methodology",
        "Empiricism Methodology",
      ],
      "class-feat": ["Known Weaknesses", "Flexible Studies", "Scalpel's Point"],
      "skill-feat": ["Cat Fall", "Forager", "Experienced Smuggler", "Acrobatic Performer", "Group Impression"],
    },
    preferredSkills: ["society", "arcana", "crafting", "medicine", "diplomacy", "stealth", "thievery", "deception"],
  }),
  {
    ...classCase({
      className: "Investigator",
      classSlug: "investigator",
      keyAbility: "int",
      expectedStepIds: [
        "class-archetype-methodology-level-1",
        "skill-training-investigator-level-1",
        "spell-choice-palatine-detective-divine-cantrip-level-1",
        "spell-choice-palatine-detective-occult-cantrip-level-1",
        "class-feat-level-4",
      ],
      preferredSelections: {
        "class-archetype-methodology-level-1": ["Palatine Detective"],
        "spell-choice-palatine-detective-divine-cantrip-level-1": ["Guidance"],
        "spell-choice-palatine-detective-occult-cantrip-level-1": ["Guidance"],
        "class-feat": ["Known Weaknesses", "Flexible Studies", "Scalpel's Point"],
        "skill-feat": ["Cat Fall", "Forager", "Experienced Smuggler", "Acrobatic Performer"],
      },
      preferredSkills: ["occultism", "society", "arcana", "crafting", "medicine", "diplomacy", "stealth"],
    }),
    id: "investigator-palatine-detective-l1-l5-apply-rerun",
    label: "Investigator Palatine Detective level 1 through 5 apply/rerun",
    preferredRuleChoices: { skill: "occultism" },
    forbiddenStepIds: [
      "class-branch-methodology-level-1",
      "class-choice-palatine-detective-skill-level-1",
      "class-feat-level-2",
    ],
    expectedItemNames: [
      "Palatine Detective",
      "Quick Identification",
      "Palatine Detective Dedication",
      "Mystic Aegis",
      "Innate Divine Spells",
      "Innate Occult Spells",
      "Guidance",
    ],
    expectedItemNameCounts: { Guidance: 2 },
    expectedSkillRanks: { occultism: 2 },
    expectedItemRuleSelections: { "Palatine Detective": { skill: "occultism" } },
    expectedItemLocations: { "Palatine Detective Dedication": "class-2" },
    forbiddenItemNames: ["Interrogation Methodology", "Forensic Medicine Methodology", "Empiricism Methodology"],
    expectedSpellcastingEntries: {
      "palatine-detective-divine-innate": {
        ability: "int",
        prepared: "innate",
        tradition: "divine",
      },
      "palatine-detective-occult-innate": {
        ability: "int",
        prepared: "innate",
        tradition: "occult",
      },
    },
    expectedItemDestinations: {
      Guidance: ["palatine-detective-divine-innate", "palatine-detective-occult-innate"],
    },
  },
  classCase({
    className: "Kineticist",
    classSlug: "kineticist",
    keyAbility: "con",
    expectedStepIds: [
      "class-choice-kinetic-gate-kineticGate-level-1",
      "class-branch-kinetic-gate-elementOne-level-1",
      "class-branch-kinetic-gate-elementTwo-level-1",
      "class-choice-gates-threshold-gatesThreshold-level-5",
      "class-branch-gates-threshold-elementFork-level-5",
    ],
    preferredSelections: {
      "class-choice-kinetic-gate-kineticGate-level-1": ["dual-gate"],
      "class-branch-kinetic-gate-elementOne-level-1": ["Fire Gate", "Earth Gate"],
      "class-branch-kinetic-gate-elementTwo-level-1": ["Air Gate", "Water Gate"],
      "class-choice-gates-threshold-gatesThreshold-level-5": ["Fork the Path", "fork", "expand"],
      "class-branch-gates-threshold-elementFork-level-5": ["Wood Gate", "Earth Gate"],
      "class-choice-gate-s-threshold-gateSThreshold-level-5": ["Fork the Path", "fork", "expand"],
      "class-branch-gate-s-threshold-elementFork-level-5": ["Wood Gate", "Earth Gate"],
      "class-feat": ["Flying Flame", "Armor in Earth"],
    },
    preferredSkills: ["nature", "athletics", "crafting", "medicine", "survival"],
  }),
  classCase({
    className: "Magus",
    classSlug: "magus",
    keyAbility: "str",
    expectedStepIds: [
      "class-branch-hybrid-study-level-1",
      "spell-choice-magus-cantrips-level-1",
      "spell-choice-magus-spellbook-rank-1-level-1",
      "spell-choice-magus-spellbook-level-2",
      "spell-choice-magus-spellbook-level-3",
      "spell-choice-magus-spellbook-level-4",
      "spell-choice-magus-spellbook-level-5",
    ],
    preferredSelections: {
      "class-branch-hybrid-study-level-1": ["Inexorable Iron", "Sparkling Targe"],
      "class-feat": ["Force Fang", "Cantrip Expansion"],
    },
    preferredSkills: ["arcana", "athletics", "crafting", "society", "acrobatics"],
  }),
  classCase({
    className: "Monk",
    classSlug: "monk",
    keyAbility: "str",
    preferredSelections: {
      "class-feat": ["Crane Stance", "Stunning Blows"],
    },
    preferredSkills: ["acrobatics", "athletics", "medicine", "religion", "stealth"],
  }),
  classCase({
    className: "Oracle",
    classSlug: "oracle",
    keyAbility: "cha",
    expectedStepIds: [
      "class-branch-mystery-level-1",
      "spell-choice-oracle-cantrips-level-1",
      "spell-choice-oracle-repertoire-rank-1-level-1",
      "spell-choice-oracle-repertoire-rank-1-level-2",
      "spell-choice-oracle-repertoire-rank-2-level-3",
      "spell-choice-oracle-repertoire-rank-2-level-4",
      "spell-choice-oracle-repertoire-rank-3-level-5",
    ],
    preferredSelections: {
      "class-branch-mystery-level-1": ["Life", "Flames"],
      "class-feat": ["Reach Spell", "Divine Access"],
    },
    preferredSkills: ["religion", "diplomacy", "medicine", "occultism", "society"],
  }),
  classCase({
    className: "Psychic",
    classSlug: "psychic",
    keyAbility: "int",
    expectedStepIds: [
      "class-branch-conscious-mind-level-1",
      "class-branch-subconscious-mind-level-1",
      "spell-choice-psychic-cantrips-level-1",
      "spell-choice-psychic-repertoire-rank-1-level-1",
      "spell-choice-psychic-repertoire-rank-1-level-2",
      "spell-choice-psychic-repertoire-rank-2-level-3",
      "spell-choice-psychic-repertoire-rank-2-level-4",
      "spell-choice-psychic-repertoire-rank-3-level-5",
    ],
    preferredSelections: {
      "class-branch-conscious-mind-level-1": ["The Distant Grasp", "The Infinite Eye"],
      "class-branch-subconscious-mind-level-1": ["Gathered Lore", "Precise Discipline"],
      "class-feat": ["Counter Thought", "Cantrip Expansion"],
    },
    preferredSkills: ["occultism", "arcana", "society", "diplomacy", "medicine"],
  }),
  classCase({
    className: "Ranger",
    classSlug: "ranger",
    keyAbility: "dex",
    expectedStepIds: ["class-branch-hunters-edge-level-1"],
    preferredSelections: {
      "class-branch-hunters-edge-level-1": ["Precision", "Flurry"],
      "class-feat": ["Monster Hunter", "Twin Takedown"],
    },
    preferredSkills: ["survival", "nature", "acrobatics", "athletics", "stealth", "medicine"],
  }),
  classCase({
    className: "Rogue",
    classSlug: "rogue",
    keyAbility: "dex",
    expectedStepIds: ["class-branch-rogues-racket-level-1"],
    preferredSelections: {
      "class-branch-rogues-racket-level-1": ["Thief", "Scoundrel"],
      "class-feat": ["Nimble Dodge", "Trap Finder"],
      "skill-feat": ["Experienced Smuggler", "Cat Fall", "Forager", "Acrobatic Performer", "Group Impression"],
    },
    preferredSkills: ["stealth", "thievery", "acrobatics", "deception", "diplomacy", "society", "athletics", "survival"],
  }),
  classCase({
    className: "Sorcerer",
    classSlug: "sorcerer",
    keyAbility: "cha",
    expectedStepIds: [
      "class-branch-bloodline-level-1",
      "spell-choice-sorcerer-cantrips-level-1",
      "spell-choice-sorcerer-repertoire-rank-1-level-1",
      "spell-choice-sorcerer-repertoire-rank-1-level-2",
      "spell-choice-sorcerer-repertoire-rank-2-level-3",
      "spell-choice-sorcerer-repertoire-rank-2-level-4",
      "spell-choice-sorcerer-repertoire-rank-3-level-5",
    ],
    preferredSelections: {
      "class-branch-bloodline-level-1": ["Bloodline: Imperial", "Bloodline: Draconic"],
      "class-feat": ["Dangerous Sorcery", "Reach Spell", "Cantrip Expansion"],
      "skill-feat": ["Group Impression", "Cat Fall", "Forager", "Acrobatic Performer"],
    },
    preferredSkills: ["arcana", "deception", "diplomacy", "intimidation", "society", "religion", "stealth"],
  }),
  classCase({
    className: "Summoner",
    classSlug: "summoner",
    keyAbility: "cha",
    expectedStepIds: [
      "class-branch-eidolon-level-1",
      "class-branch-evolution-feat-level-1",
      "spell-choice-summoner-cantrips-level-1",
      "spell-choice-summoner-repertoire-rank-1-level-1",
      "spell-choice-summoner-repertoire-rank-1-level-2",
      "spell-choice-summoner-repertoire-rank-2-level-3",
      "spell-choice-summoner-repertoire-rank-2-level-4",
      "spell-choice-summoner-repertoire-rank-3-level-5",
    ],
    preferredSelections: {
      "class-branch-eidolon-level-1": ["Dragon Eidolon", "Angel Eidolon"],
      "class-branch-evolution-feat-level-1": ["Advanced Weaponry", "Energy Heart"],
      "class-feat": ["Reinforce Eidolon", "Lifelink Surge", "Skilled Partner"],
    },
    preferredSkills: ["arcana", "nature", "occultism", "religion", "diplomacy", "society"],
  }),
  classCase({
    className: "Swashbuckler",
    classSlug: "swashbuckler",
    keyAbility: "dex",
    expectedStepIds: ["class-branch-swashbucklers-style-level-1"],
    preferredSelections: {
      "class-branch-swashbucklers-style-level-1": ["Fencer", "Wit"],
      "class-feat": ["One for All", "Flying Blade"],
    },
    preferredSkills: ["acrobatics", "athletics", "diplomacy", "deception", "intimidation", "performance"],
  }),
  classCase({
    className: "Thaumaturge",
    classSlug: "thaumaturge",
    keyAbility: "cha",
    expectedStepIds: [
      "class-choice-initiate-benefit-wand-initiateBenefitWand-level-1",
      "class-branch-first-implement-and-esoterica-level-1",
      "class-branch-second-implement-level-5",
    ],
    preferredSelections: {
      "class-branch-first-implement-and-esoterica-level-1": ["Amulet", "Weapon"],
      "class-branch-second-implement-level-5": ["Wand", "Tome"],
      "class-feat": ["Diverse Lore", "Scroll Thaumaturgy"],
    },
    preferredSkills: ["esoteric-lore", "arcana", "occultism", "religion", "society", "diplomacy"],
  }),
  classCase({
    className: "Witch",
    classSlug: "witch",
    keyAbility: "int",
    expectedStepIds: [
      "class-branch-patron-level-1",
      "spell-choice-witch-cantrips-level-1",
      "spell-choice-witch-rank-1-level-1",
      "spell-choice-witch-patron-lesson-level-1",
      "spell-choice-witch-familiar-level-2",
      "spell-choice-witch-familiar-level-3",
      "spell-choice-witch-familiar-level-4",
      "spell-choice-witch-familiar-level-5",
    ],
    expectedSpellChoiceCounts: {
      "spell-choice-witch-cantrips-level-1": 10,
      "spell-choice-witch-rank-1-level-1": 5,
      "spell-choice-witch-patron-lesson-level-1": 1,
      "spell-choice-witch-familiar-level-2": 2,
      "spell-choice-witch-familiar-level-3": 2,
      "spell-choice-witch-familiar-level-4": 2,
      "spell-choice-witch-familiar-level-5": 2,
    },
    preferredSelections: {
      "class-branch-patron-level-1": ["Spinner of Threads", "Faith's Flamekeeper"],
      "class-feat": ["Cackle", "Widen Spell"],
      "spell-choice": deepOccultSpells,
    },
    preferredSkills: ["occultism", "arcana", "nature", "religion", "crafting", "society"],
  }),
  classCase({
    className: "Wizard",
    classSlug: "wizard",
    keyAbility: "int",
    expectedStepIds: [
      "class-branch-arcane-school-level-1",
      "class-branch-arcane-thesis-level-1",
      "spell-choice-wizard-curriculum-rank-1-level-1",
      "spell-choice-wizard-spellbook-cantrips-level-1",
      "spell-choice-wizard-spellbook-rank-1-level-1",
      "spell-choice-wizard-spellbook-level-2",
      "spell-choice-wizard-curriculum-rank-2-level-3",
      "spell-choice-wizard-spellbook-level-3",
      "spell-choice-wizard-spellbook-level-4",
      "spell-choice-wizard-curriculum-rank-3-level-5",
      "spell-choice-wizard-spellbook-level-5",
    ],
    preferredSelections: {
      "class-feat": ["Reach Spell", "Counterspell", "Cantrip Expansion"],
      "skill-feat": ["Recognize Spell", "Cat Fall", "Forager", "Acrobatic Performer"],
    },
    preferredSkills: ["arcana", "crafting", "society", "occultism", "religion", "medicine", "nature"],
  }),
  depthCase({
    id: "fighter-depth-l1-l10-apply-rerun",
    label: "Fighter depth verification level 1 through 10 apply/rerun",
    className: "Fighter",
    classSlug: "fighter",
    keyAbility: "str",
    targetLevel: 10,
    expectedStepIds: ["class-choice-fighter-weapon-mastery-fighterWeaponMastery-level-5"],
    preferredSelections: {
      "ancestry-feat": deepAncestry,
      "general-feat": deepGeneral,
      "skill-feat": deepSkillFeats,
      "class-feat": [
        "Reactive Shield",
        "Intimidating Strike",
        "Quick Reversal",
        "Dazing Blow",
        "Felling Strike",
        "Blind-Fight",
      ],
    },
    preferredSkills: ["athletics", "acrobatics", "survival", "intimidation", "religion", "stealth"],
    expectedSkillIncreaseSelections: {
      "skill-increase-level-3": "athletics",
      "skill-increase-level-5": "acrobatics",
      "skill-increase-level-7": "athletics",
      "skill-increase-level-9": "acrobatics",
    },
    expectedSkillRanks: { athletics: 3, acrobatics: 3 },
  }),
  depthCase({
    id: "wizard-depth-l1-l10-apply-rerun",
    label: "Wizard prepared-caster depth verification level 1 through 10 apply/rerun",
    className: "Wizard",
    classSlug: "wizard",
    keyAbility: "int",
    targetLevel: 10,
    expectedStepIds: [
      "class-branch-arcane-school-level-1",
      "class-branch-arcane-thesis-level-1",
      "spell-choice-wizard-curriculum-rank-5-level-9",
      "spell-choice-wizard-spellbook-level-10",
    ],
    expectedPickerOptions: {
      "spell-choice-wizard-spellbook-level-10": {
        minRank: 1,
        maxRank: 5,
        highestRank: 5,
      },
    },
    preferredSelections: {
      "ancestry-feat": deepAncestry,
      "general-feat": deepGeneral,
      "skill-feat": deepSkillFeats,
      "class-branch-arcane-school-level-1": ["School of Battle Magic"],
      "class-branch-arcane-thesis-level-1": ["Spell Blending", "Spell Substitution"],
      "class-feat": ["Reach Spell", "Counterspell (Prepared)", "Cantrip Expansion", "Spell Protection Array"],
      "spell-choice": deepArcaneSpells,
    },
    preferredSkills: ["arcana", "crafting", "society", "occultism", "religion", "medicine", "nature"],
    expectedSkillIncreaseSelections: {
      "skill-increase-level-3": "arcana",
      "skill-increase-level-5": "crafting",
      "skill-increase-level-7": "arcana",
      "skill-increase-level-9": "crafting",
    },
    expectedSkillRanks: { arcana: 3, crafting: 3 },
  }),
  depthCase({
    id: "bard-depth-l1-l10-apply-rerun",
    label: "Bard spontaneous-caster depth verification level 1 through 10 apply/rerun",
    className: "Bard",
    classSlug: "bard",
    keyAbility: "cha",
    targetLevel: 10,
    expectedStepIds: [
      "class-branch-muses-level-1",
      "spell-choice-bard-repertoire-rank-5-level-9",
      "spell-choice-bard-repertoire-rank-5-level-10",
    ],
    expectedPickerOptions: {
      "spell-choice-bard-repertoire-rank-5-level-10": {
        minRank: 5,
        maxRank: 5,
        highestRank: 5,
      },
    },
    preferredSelections: {
      "ancestry-feat": deepAncestry,
      "general-feat": deepGeneral,
      "skill-feat": deepSkillFeats,
      "class-branch-muses-level-1": ["Maestro"],
      "class-feat": [
        "Reach Spell",
        "Cantrip Expansion",
        "Bardic Lore",
        "Hymn of Healing",
        "Dirge of Doom",
        "Eclectic Skill",
      ],
      "spell-choice": deepOccultSpells,
    },
    preferredSkills: ["occultism", "performance", "diplomacy", "deception", "society", "acrobatics"],
    expectedSkillIncreaseSelections: {
      "skill-increase-level-3": "occultism",
      "skill-increase-level-5": "performance",
      "skill-increase-level-7": "occultism",
      "skill-increase-level-9": "performance",
    },
    expectedSkillRanks: { occultism: 3, performance: 3 },
  }),
  depthCase({
    id: "magus-depth-l1-l10-apply-rerun",
    label: "Magus bounded-caster depth verification level 1 through 10 apply/rerun",
    className: "Magus",
    classSlug: "magus",
    keyAbility: "str",
    targetLevel: 10,
    expectedStepIds: [
      "class-branch-hybrid-study-level-1",
      "spell-choice-magus-spellbook-level-9",
      "spell-choice-magus-spellbook-level-10",
    ],
    expectedPickerOptions: {
      "spell-choice-magus-spellbook-level-10": {
        minRank: 1,
        maxRank: 5,
        highestRank: 5,
      },
    },
    preferredSelections: {
      "ancestry-feat": deepAncestry,
      "general-feat": deepGeneral,
      "skill-feat": deepSkillFeats,
      "class-branch-hybrid-study-level-1": ["Inexorable Iron"],
      "class-feat": ["Force Fang", "Cantrip Expansion", "Expansive Spellstrike", "Reactive Strike"],
      "spell-choice": deepArcaneSpells,
    },
    preferredSkills: ["arcana", "athletics", "crafting", "society", "acrobatics"],
    expectedSkillIncreaseSelections: {
      "skill-increase-level-3": "arcana",
      "skill-increase-level-5": "athletics",
      "skill-increase-level-7": "arcana",
      "skill-increase-level-9": "athletics",
    },
    expectedSkillRanks: { arcana: 3, athletics: 3 },
  }),
  depthCase({
    id: "investigator-depth-l1-l10-apply-rerun",
    label: "Investigator skill-heavy depth verification level 1 through 10 apply/rerun",
    className: "Investigator",
    classSlug: "investigator",
    keyAbility: "int",
    targetLevel: 10,
    expectedStepIds: ["class-archetype-methodology-level-1", "class-branch-methodology-level-1"],
    preferredSelections: {
      "ancestry-feat": deepAncestry,
      "general-feat": deepGeneral,
      "skill-feat": deepSkillFeats,
      "class-archetype-methodology-level-1": ["Standard class path"],
      "class-branch-methodology-level-1": ["Interrogation Methodology"],
      "class-feat": [
        "Known Weaknesses",
        "Flexible Studies",
        "Scalpel's Point",
        "Thorough Research",
        "Blind-Fight",
      ],
    },
    preferredSkills: ["society", "arcana", "crafting", "medicine", "diplomacy", "stealth", "thievery", "deception"],
    expectedSkillIncreaseSelections: {
      "skill-increase-level-3": "society",
      "skill-increase-level-5": "arcana",
      "skill-increase-level-7": "society",
      "skill-increase-level-9": "arcana",
    },
    expectedSkillRanks: { society: 3, arcana: 3 },
  }),
  depthCase({
    id: "fighter-depth-l1-l20-apply-rerun",
    label: "Fighter depth verification level 1 through 20 apply/rerun",
    className: "Fighter",
    classSlug: "fighter",
    keyAbility: "str",
    targetLevel: 20,
    expectedStepIds: ["class-choice-fighter-weapon-mastery-fighterWeaponMastery-level-5"],
    preferredSelections: {
      "ancestry-feat": deepAncestry,
      "general-feat": deepGeneral,
      "skill-feat": deepSkillFeats,
      "class-feat": [
        "Reactive Shield",
        "Intimidating Strike",
        "Quick Reversal",
        "Dazing Blow",
        "Felling Strike",
        "Blind-Fight",
        "Disruptive Stance",
        "Crashing Slam",
        "Whirlwind Strike",
        "Overwhelming Blow",
        "Boundless Reprisals",
      ],
    },
    preferredSkills: ["athletics", "acrobatics", "survival", "intimidation", "religion", "stealth"],
    expectedSkillIncreaseSelections: {
      "skill-increase-level-3": "athletics",
      "skill-increase-level-5": "acrobatics",
      "skill-increase-level-7": "athletics",
      "skill-increase-level-9": "acrobatics",
      "skill-increase-level-11": "survival",
      "skill-increase-level-13": "survival",
      "skill-increase-level-15": "athletics",
      "skill-increase-level-17": "acrobatics",
      "skill-increase-level-19": "survival",
    },
    expectedSkillRanks: { athletics: 4, acrobatics: 4, survival: 4 },
  }),
];

export const gradualBoostsSmokeCases = [
  {
    ...classCase({
      className: "Fighter",
      classSlug: "fighter",
      keyAbility: "str",
      expectedStepIds: [
        "ability-boosts-level-2",
        "ability-boosts-level-3",
        "ability-boosts-level-4",
        "ability-boosts-level-5",
        "class-choice-fighter-weapon-mastery-fighterWeaponMastery-level-5",
      ],
      preferredSelections: {
        "class-feat": ["Reactive Shield", "Intimidating Strike", "Quick Reversal"],
        "skill-feat": ["Cat Fall", "Forager", "Acrobatic Performer", "Group Impression", "Quick Jump"],
      },
      preferredSkills: ["athletics", "acrobatics", "survival", "intimidation", "religion", "stealth"],
    }),
    id: "fighter-gradual-boosts-l1-l5-apply-rerun",
    label: "Fighter with Gradual Ability Boosts level 1 through 5 apply/rerun",
    gradualBoostsVariant: true,
    expectedBoostBatchCounts: { 1: 4, 5: 4 },
    forbiddenBoostBatchLevels: [2, 3, 4],
  },
];

export const applySafetySmokeCases = [
  {
    ...classCase({
      className: "Fighter",
      classSlug: "fighter",
      keyAbility: "str",
      expectedStepIds: ["class-choice-fighter-weapon-mastery-fighterWeaponMastery-level-5"],
      preferredSelections: {
        "class-feat": ["Reactive Shield", "Intimidating Strike", "Quick Reversal"],
        "skill-feat": ["Cat Fall", "Forager", "Acrobatic Performer", "Group Impression", "Quick Jump"],
      },
      preferredSkills: ["athletics", "acrobatics", "survival", "intimidation", "religion", "stealth"],
    }),
    id: "fighter-apply-safety-failure-retry",
    label: "Fighter late apply failure and idempotent retry",
    expectedPreApply: {
      level: 1,
      itemCount: 0,
      moduleState: {
        version: 2,
        lastAppliedAt: null,
        lastTargetLevel: null,
        completedStepIds: [],
        existingCharacterHistory: null,
      },
    },
    expectedPreStepIds: [
      "ancestry-level-1",
      "heritage-level-1",
      "background-level-1",
      "class-level-1",
      "ancestry-feat-level-1",
      "ability-boosts-level-1",
      "skill-training-fighter-level-1",
      "language-choice-level-1",
      "class-feat-level-1",
      "class-feat-level-2",
      "skill-feat-level-2",
      "general-feat-level-3",
      "skill-increase-level-3",
      "class-feat-level-4",
      "skill-feat-level-4",
      "ancestry-feat-level-5",
      "ability-boosts-level-5",
      "class-choice-fighter-weapon-mastery-fighterWeaponMastery-level-5",
      "skill-increase-level-5",
    ],
    expectedRetryStepIds: [
      "skill-training-fighter-level-1",
      "language-choice-level-1",
      "skill-increase-level-3",
      "ability-boosts-level-5",
      "class-choice-fighter-weapon-mastery-fighterWeaponMastery-level-5",
      "skill-increase-level-5",
    ],
    expectedCompletedReceiptCounts: {
      "singleton-replacements": { created: 9, deleted: 0, updated: 0 },
      "singleton-system-grants": { created: 0, deleted: 0, updated: 0 },
      "singleton-explicit-grants": { created: 0, deleted: 0, updated: 0 },
      "singleton-choice-persistence-early": { created: 0, deleted: 0, updated: 0 },
      "skill-training-items": { created: 1, deleted: 0, updated: 1 },
      "class-archetype": { created: 0, deleted: 0, updated: 0 },
      "class-branches": { created: 0, deleted: 0, updated: 0 },
      "class-feature-choices": { created: 1, deleted: 0, updated: 0 },
      "native-spellcasting-before-feats": { created: 0, deleted: 0, updated: 0 },
      "feat-selections": { created: 8, deleted: 0, updated: 0 },
      "singleton-choice-persistence-late": { created: 0, deleted: 0, updated: 0 },
      "spell-choices": { created: 0, deleted: 0, updated: 0 },
      "native-spellcasting-after-spells": { created: 0, deleted: 0, updated: 0 },
      "boost-item-updates": { created: 0, deleted: 0, updated: 1 },
    },
    expectedCompletedReceiptIdentities: {
      "singleton-replacements": {
        created: [
          "action||Compendium.pf2e.actionspf2e.Item.KAVf7AmRnbCAHrkT|Reactive Strike",
          "ancestry|ancestry-level-1|Compendium.pf2e.ancestries.Item.IiG7DgeLWYrSNXuX|Human",
          "background|background-level-1|Compendium.pf2e.backgrounds.Item.CAjQrHZZbALE7Qjy|Acolyte",
          "class|class-level-1|Compendium.pf2e.classes.Item.8zn3cD6GSmoo1LW4|Fighter",
          "feat||Compendium.pf2e.classfeatures.Item.eZNCckLzbH3GyncH|Shield Block",
          "feat||Compendium.pf2e.classfeatures.Item.hmShTfPOcTaKgbf4|Reactive Strike",
          "feat||Compendium.pf2e.feats-srd.Item.jM72TjJ965jocBV8|Shield Block",
          "feat||Compendium.pf2e.feats-srd.Item.x7EMZNMavris2aHY|Student of the Canon",
          "heritage|heritage-level-1|Compendium.pf2e.heritages.Item.KO33MNyY9VqNQmbZ|Wintertouched Human",
        ],
      },
      "skill-training-items": {
        created: ["lore|skill-training-fighter-level-1||Scribing Lore"],
        updated: ["class|class-level-1|Compendium.pf2e.classes.Item.8zn3cD6GSmoo1LW4|Fighter"],
      },
      "class-feature-choices": {
        created: [
          "feat|class-choice-fighter-weapon-mastery-fighterWeaponMastery-level-5|Compendium.pf2e.classfeatures.Item.gApJtAdNb9ST4Ms9|Fighter Weapon Mastery (Axe)",
        ],
      },
      "feat-selections": {
        created: [
          "feat|ancestry-feat-level-1|Compendium.pf2e.feats-srd.Item.lwLcUHQMOqfaNND4|Cooperative Nature",
          "feat|ancestry-feat-level-5|Compendium.pf2e.feats-srd.Item.RmiMUZlae6yGUyXY|Haughty Obstinacy",
          "feat|class-feat-level-1|Compendium.pf2e.feats-srd.Item.w8Ycgeq2zfyshtoS|Reactive Shield",
          "feat|class-feat-level-2|Compendium.pf2e.feats-srd.Item.lkcM4V3VDAtjlR9P|Intimidating Strike",
          "feat|class-feat-level-4|Compendium.pf2e.feats-srd.Item.SnIx3FhBuuq6AZD0|Quick Reversal",
          "feat|general-feat-level-3|Compendium.pf2e.feats-srd.Item.AmP0qu7c5dlBSath|Toughness",
          "feat|skill-feat-level-2|Compendium.pf2e.feats-srd.Item.LQw0yIMDUJJkq1nD|Cat Fall",
          "feat|skill-feat-level-4|Compendium.pf2e.feats-srd.Item.8qebBeOJsyRIchcu|Forager",
        ],
      },
      "boost-item-updates": {
        updated: [
          "ancestry|ancestry-level-1|Compendium.pf2e.ancestries.Item.IiG7DgeLWYrSNXuX|Human",
        ],
      },
    },
    expectedBoostBatchCounts: { 1: 4, 5: 4 },
    expectedItemCount: 20,
    expectedItemIdentities: [
      "action||Compendium.pf2e.actionspf2e.Item.KAVf7AmRnbCAHrkT|Reactive Strike",
      "ancestry|ancestry-level-1|Compendium.pf2e.ancestries.Item.IiG7DgeLWYrSNXuX|Human",
      "background|background-level-1|Compendium.pf2e.backgrounds.Item.CAjQrHZZbALE7Qjy|Acolyte",
      "class|class-level-1|Compendium.pf2e.classes.Item.8zn3cD6GSmoo1LW4|Fighter",
      "feat||Compendium.pf2e.classfeatures.Item.eZNCckLzbH3GyncH|Shield Block",
      "feat||Compendium.pf2e.classfeatures.Item.GJKJafDGuX4BeAeN|Bravery",
      "feat||Compendium.pf2e.classfeatures.Item.hmShTfPOcTaKgbf4|Reactive Strike",
      "feat||Compendium.pf2e.feats-srd.Item.jM72TjJ965jocBV8|Shield Block",
      "feat||Compendium.pf2e.feats-srd.Item.x7EMZNMavris2aHY|Student of the Canon",
      "feat|ancestry-feat-level-1|Compendium.pf2e.feats-srd.Item.lwLcUHQMOqfaNND4|Cooperative Nature",
      "feat|ancestry-feat-level-5|Compendium.pf2e.feats-srd.Item.RmiMUZlae6yGUyXY|Haughty Obstinacy",
      "feat|class-choice-fighter-weapon-mastery-fighterWeaponMastery-level-5|Compendium.pf2e.classfeatures.Item.gApJtAdNb9ST4Ms9|Fighter Weapon Mastery (Axe)",
      "feat|class-feat-level-1|Compendium.pf2e.feats-srd.Item.w8Ycgeq2zfyshtoS|Reactive Shield",
      "feat|class-feat-level-2|Compendium.pf2e.feats-srd.Item.lkcM4V3VDAtjlR9P|Intimidating Strike",
      "feat|class-feat-level-4|Compendium.pf2e.feats-srd.Item.SnIx3FhBuuq6AZD0|Quick Reversal",
      "feat|general-feat-level-3|Compendium.pf2e.feats-srd.Item.AmP0qu7c5dlBSath|Toughness",
      "feat|skill-feat-level-2|Compendium.pf2e.feats-srd.Item.LQw0yIMDUJJkq1nD|Cat Fall",
      "feat|skill-feat-level-4|Compendium.pf2e.feats-srd.Item.8qebBeOJsyRIchcu|Forager",
      "heritage|heritage-level-1|Compendium.pf2e.heritages.Item.KO33MNyY9VqNQmbZ|Wintertouched Human",
      "lore|skill-training-fighter-level-1||Scribing Lore",
    ],
    expectedItemSemanticIdentities: [
      "action||Compendium.pf2e.actionspf2e.Item.KAVf7AmRnbCAHrkT|Reactive Strike::destination=::location=::training=::grant=source:Compendium.pf2e.classfeatures.Item.hmShTfPOcTaKgbf4::container=::quantity=::physical=false::currency=false",
      "ancestry|ancestry-level-1|Compendium.pf2e.ancestries.Item.IiG7DgeLWYrSNXuX|Human::destination=::location=::training=::grant=::container=::quantity=::physical=false::currency=false",
      "background|background-level-1|Compendium.pf2e.backgrounds.Item.CAjQrHZZbALE7Qjy|Acolyte::destination=::location=::training=::grant=::container=::quantity=::physical=false::currency=false",
      "class|class-level-1|Compendium.pf2e.classes.Item.8zn3cD6GSmoo1LW4|Fighter::destination=::location=::training=::grant=::container=::quantity=::physical=false::currency=false",
      "feat||Compendium.pf2e.classfeatures.Item.eZNCckLzbH3GyncH|Shield Block::destination=::location=source:Compendium.pf2e.classes.Item.8zn3cD6GSmoo1LW4::training=::grant=::container=::quantity=::physical=false::currency=false",
      "feat||Compendium.pf2e.classfeatures.Item.GJKJafDGuX4BeAeN|Bravery::destination=::location=source:Compendium.pf2e.classes.Item.8zn3cD6GSmoo1LW4::training=::grant=::container=::quantity=::physical=false::currency=false",
      "feat||Compendium.pf2e.classfeatures.Item.hmShTfPOcTaKgbf4|Reactive Strike::destination=::location=source:Compendium.pf2e.classes.Item.8zn3cD6GSmoo1LW4::training=::grant=::container=::quantity=::physical=false::currency=false",
      "feat||Compendium.pf2e.feats-srd.Item.jM72TjJ965jocBV8|Shield Block::destination=::location=::training=::grant=source:Compendium.pf2e.classfeatures.Item.eZNCckLzbH3GyncH::container=::quantity=::physical=false::currency=false",
      "feat||Compendium.pf2e.feats-srd.Item.x7EMZNMavris2aHY|Student of the Canon::destination=::location=source:Compendium.pf2e.backgrounds.Item.CAjQrHZZbALE7Qjy::training=::grant=::container=::quantity=::physical=false::currency=false",
      "feat|ancestry-feat-level-1|Compendium.pf2e.feats-srd.Item.lwLcUHQMOqfaNND4|Cooperative Nature::destination=::location=literal:ancestry-1::training=::grant=::container=::quantity=::physical=false::currency=false",
      "feat|ancestry-feat-level-5|Compendium.pf2e.feats-srd.Item.RmiMUZlae6yGUyXY|Haughty Obstinacy::destination=::location=literal:ancestry-5::training=::grant=::container=::quantity=::physical=false::currency=false",
      "feat|class-choice-fighter-weapon-mastery-fighterWeaponMastery-level-5|Compendium.pf2e.classfeatures.Item.gApJtAdNb9ST4Ms9|Fighter Weapon Mastery (Axe)::destination=::location=source:Compendium.pf2e.classes.Item.8zn3cD6GSmoo1LW4::training=::grant=::container=::quantity=::physical=false::currency=false",
      "feat|class-feat-level-1|Compendium.pf2e.feats-srd.Item.w8Ycgeq2zfyshtoS|Reactive Shield::destination=::location=literal:class-1::training=::grant=::container=::quantity=::physical=false::currency=false",
      "feat|class-feat-level-2|Compendium.pf2e.feats-srd.Item.lkcM4V3VDAtjlR9P|Intimidating Strike::destination=::location=literal:class-2::training=::grant=::container=::quantity=::physical=false::currency=false",
      "feat|class-feat-level-4|Compendium.pf2e.feats-srd.Item.SnIx3FhBuuq6AZD0|Quick Reversal::destination=::location=literal:class-4::training=::grant=::container=::quantity=::physical=false::currency=false",
      "feat|general-feat-level-3|Compendium.pf2e.feats-srd.Item.AmP0qu7c5dlBSath|Toughness::destination=::location=literal:general-3::training=::grant=::container=::quantity=::physical=false::currency=false",
      "feat|skill-feat-level-2|Compendium.pf2e.feats-srd.Item.LQw0yIMDUJJkq1nD|Cat Fall::destination=::location=literal:skill-2::training=::grant=::container=::quantity=::physical=false::currency=false",
      "feat|skill-feat-level-4|Compendium.pf2e.feats-srd.Item.8qebBeOJsyRIchcu|Forager::destination=::location=literal:skill-4::training=::grant=::container=::quantity=::physical=false::currency=false",
      "heritage|heritage-level-1|Compendium.pf2e.heritages.Item.KO33MNyY9VqNQmbZ|Wintertouched Human::destination=::location=::training=::grant=::container=::quantity=::physical=false::currency=false",
      "lore|skill-training-fighter-level-1||Scribing Lore::destination=::location=::training=fixed:0::grant=::container=::quantity=::physical=false::currency=false",
    ],
    expectedItemNameCounts: {
      Acolyte: 1,
      Bravery: 1,
      "Cat Fall": 1,
      "Cooperative Nature": 1,
      Fighter: 1,
      "Fighter Weapon Mastery (Axe)": 1,
      Forager: 1,
      "Haughty Obstinacy": 1,
      Human: 1,
      "Intimidating Strike": 1,
      "Quick Reversal": 1,
      "Reactive Shield": 1,
      "Reactive Strike": 2,
      "Scribing Lore": 1,
      "Shield Block": 2,
      "Student of the Canon": 1,
      Toughness: 1,
      "Wintertouched Human": 1,
    },
    expectedSkillRanks: { acrobatics: 2, athletics: 2 },
    expectedExactSkillRanks: {
      acrobatics: 2,
      arcana: 0,
      athletics: 2,
      crafting: 0,
      deception: 0,
      diplomacy: 0,
      intimidation: 1,
      medicine: 0,
      nature: 0,
      occultism: 0,
      performance: 0,
      religion: 1,
      society: 0,
      stealth: 0,
      survival: 1,
      thievery: 0,
      "scribing-lore": 1,
    },
    expectedAbilityBoosts: {
      1: ["str", "dex", "con", "wis"],
      5: ["str", "dex", "con", "wis"],
      10: [],
      15: [],
      20: [],
      ancestry: ["str", "dex"],
      background: ["wis", "con"],
      class: "str",
    },
    expectedFinalActorUpdatePaths: [
      "flags.wayfinder-pf2e.draft",
      "flags.wayfinder-pf2e.state",
    ],
    applySafetyFailureCheckpoint: {
      checkpointId: "phase:source-flag-restoration:before",
      occurrence: 1,
    },
  },
];
