const commonAncestry = ["Cooperative Nature", "Haughty Obstinacy"];
const commonGeneral = ["Toughness", "Fleet"];
const commonSkills = ["acrobatics", "athletics", "crafting", "diplomacy", "medicine", "nature", "religion", "society"];
const commonSkillFeats = ["Cat Fall", "Forager", "Acrobatic Performer", "Group Impression", "Quick Jump"];

export const expectedPf2eClassSlugs = [
  "alchemist",
  "animist",
  "barbarian",
  "bard",
  "champion",
  "cleric",
  "commander",
  "druid",
  "exemplar",
  "fighter",
  "guardian",
  "gunslinger",
  "inventor",
  "investigator",
  "kineticist",
  "magus",
  "monk",
  "oracle",
  "psychic",
  "ranger",
  "rogue",
  "sorcerer",
  "summoner",
  "swashbuckler",
  "thaumaturge",
  "witch",
  "wizard",
];

function classCase({
  className,
  classSlug,
  keyAbility,
  expectedStepIds = [],
  preferredSelections = {},
  preferredSkills = commonSkills,
  deityName,
  spellChoiceMode,
}) {
  return {
    id: `${classSlug}-l1-l5-apply-rerun`,
    label: `${className} level 1 through 5 apply/rerun`,
    className,
    classSlug,
    deityName,
    keyAbility,
    targetLevel: 5,
    spellChoiceMode,
    expectedStepIds,
    preferredSelections: {
      "ancestry-feat": commonAncestry,
      "general-feat": commonGeneral,
      "skill-feat": commonSkillFeats,
      ...preferredSelections,
    },
    preferredSkills,
  };
}

export const smokeCases = [
  classCase({
    className: "Alchemist",
    classSlug: "alchemist",
    keyAbility: "int",
    expectedStepIds: ["class-branch-research-field-level-1"],
    preferredSelections: {
      "class-branch-research-field-level-1": ["Bomber", "Chirurgeon"],
      "class-feat": ["Quick Bomber", "Far Lobber"],
    },
    preferredSkills: ["crafting", "medicine", "nature", "society", "arcana", "thievery"],
  }),
  classCase({
    className: "Animist",
    classSlug: "animist",
    keyAbility: "wis",
    expectedStepIds: [
      "class-branch-animistic-practice-level-1",
      "spell-choice-animist-cantrips-level-1",
      "spell-choice-animist-rank-1-level-1",
    ],
    preferredSelections: {
      "class-branch-animistic-practice-level-1": ["Medium", "Seer"],
      "class-feat": ["Grudge Strike", "Restorative Familiar"],
    },
    preferredSkills: ["religion", "nature", "occultism", "medicine", "society"],
  }),
  classCase({
    className: "Barbarian",
    classSlug: "barbarian",
    keyAbility: "str",
    expectedStepIds: ["class-branch-instinct-level-1"],
    preferredSelections: {
      "class-branch-instinct-level-1": ["Fury Instinct", "Animal Instinct"],
      "class-feat": ["Sudden Charge", "Raging Intimidation"],
    },
    preferredSkills: ["athletics", "intimidation", "survival", "acrobatics", "nature"],
  }),
  classCase({
    className: "Bard",
    classSlug: "bard",
    keyAbility: "cha",
    expectedStepIds: [
      "class-branch-muses-level-1",
      "spell-choice-bard-cantrips-level-1",
      "spell-choice-bard-repertoire-rank-1-level-1",
      "spell-choice-bard-repertoire-rank-1-level-2",
      "spell-choice-bard-repertoire-rank-2-level-3",
      "spell-choice-bard-repertoire-rank-2-level-4",
      "spell-choice-bard-repertoire-rank-3-level-5",
    ],
    preferredSelections: {
      "class-branch-muses-level-1": ["Maestro", "Enigma"],
      "class-feat": ["Reach Spell", "Cantrip Expansion", "Bardic Lore", "Hymn of Healing"],
    },
    preferredSkills: ["occultism", "performance", "diplomacy", "deception", "society", "acrobatics"],
  }),
  {
    ...classCase({
      className: "Bard",
      classSlug: "bard",
      keyAbility: "cha",
      expectedStepIds: [
        "class-branch-muses-level-1",
        "flag-choice-none-feat-multifarious-muse-muse-level-2",
        "grant-choice-none-feat-multifarious-muse-feat-level-2",
        "spell-choice-bard-cantrips-level-1",
        "spell-choice-bard-repertoire-rank-1-level-1",
        "spell-choice-bard-repertoire-rank-1-level-2",
        "spell-choice-bard-repertoire-rank-2-level-3",
        "spell-choice-bard-repertoire-rank-2-level-4",
        "spell-choice-bard-repertoire-rank-3-level-5",
      ],
      preferredSelections: {
        "class-branch-muses-level-1": ["Maestro"],
        "class-feat-level-2": ["Multifarious Muse"],
        "class-feat-level-4": ["Cantrip Expansion", "Reach Spell"],
        "flag-choice-none-feat-multifarious-muse-muse-level-2": ["Enigma", "Polymath"],
        "grant-choice-none-feat-multifarious-muse-feat-level-2": ["Bardic Lore", "Hymn of Healing"],
        "class-feat": ["Cantrip Expansion", "Reach Spell", "Hymn of Healing"],
      },
      preferredSkills: ["occultism", "performance", "diplomacy", "deception", "society", "acrobatics"],
    }),
    id: "bard-multifarious-muse-l1-l5-apply-rerun",
    label: "Bard with Multifarious Muse flag choice level 1 through 5 apply/rerun",
  },
  classCase({
    className: "Champion",
    classSlug: "champion",
    deityName: "Sarenrae",
    keyAbility: "str",
    spellChoiceMode: "pf2e-granted",
    expectedStepIds: [
      "class-choice-deity-champion-sanctification-level-1",
      "class-branch-cause-level-1",
      "class-branch-blessing-of-the-devoted-level-3",
    ],
    preferredSelections: {
      deity: ["Sarenrae", "Pharasma", "Abadar"],
      "class-branch-cause-level-1": ["Justice", "Liberation"],
      "class-branch-blessing-of-the-devoted-level-3": ["Blessed Armament", "Blessed Shield"],
      "class-feat": ["Deity's Domain", "Ranged Reprisal"],
    },
    preferredSkills: ["religion", "athletics", "diplomacy", "medicine", "society"],
  }),
  classCase({
    className: "Cleric",
    classSlug: "cleric",
    deityName: "Sarenrae",
    keyAbility: "wis",
    expectedStepIds: [
      "class-choice-divine-font-divineFont-level-1",
      "class-choice-deity-cleric-sanctification-level-1",
      "class-branch-doctrine-level-1",
      "spell-choice-cleric-cantrips-level-1",
      "spell-choice-cleric-rank-1-level-1",
    ],
    preferredSelections: {
      deity: ["Sarenrae", "Pharasma", "Abadar"],
      "class-branch-doctrine-level-1": ["Cloistered Cleric", "Warpriest"],
      "class-feat": ["Healing Hands", "Reach Spell", "Sap Life"],
      "skill-feat": ["Forager", "Recognize Spell", "Cat Fall", "Acrobatic Performer"],
    },
    preferredSkills: ["religion", "medicine", "diplomacy", "nature", "society", "athletics", "survival"],
  }),
  classCase({
    className: "Commander",
    classSlug: "commander",
    keyAbility: "str",
    expectedStepIds: [
      "class-branch-tactics-firstTactic-level-1",
      "class-branch-tactics-secondTactic-level-1",
      "class-branch-tactics-thirdTactic-level-1",
      "class-branch-tactics-fourthTactic-level-1",
      "class-branch-tactics-fifthTactic-level-1",
    ],
    preferredSelections: {
      "class-branch-tactics-firstTactic-level-1": ["Coordinating Maneuvers"],
      "class-branch-tactics-secondTactic-level-1": ["Defensive Retreat"],
      "class-branch-tactics-thirdTactic-level-1": ["Double Team"],
      "class-branch-tactics-fourthTactic-level-1": ["End It!"],
      "class-branch-tactics-fifthTactic-level-1": ["Gather to Me!"],
      "class-feat": ["Combat Assessment", "Defensive Advance"],
    },
    preferredSkills: ["warfare-lore", "athletics", "diplomacy", "intimidation", "society", "survival"],
  }),
  classCase({
    className: "Druid",
    classSlug: "druid",
    keyAbility: "wis",
    expectedStepIds: [
      "class-choice-voice-of-nature-feat-level-1",
      "class-branch-druidic-order-level-1",
      "spell-choice-druid-cantrips-level-1",
      "spell-choice-druid-rank-1-level-1",
    ],
    preferredSelections: {
      "class-branch-druidic-order-level-1": ["Storm Order", "Leaf Order"],
      "grant-choice-none-feat-order-explorer-order-level-2": ["Leaf Order"],
      "class-feat": ["Order Explorer", "Reach Spell"],
    },
    preferredSkills: ["nature", "survival", "medicine", "athletics", "diplomacy"],
  }),
  classCase({
    className: "Exemplar",
    classSlug: "exemplar",
    keyAbility: "str",
    expectedStepIds: [
      "class-branch-divine-spark-and-ikons-firstIkon-level-1",
      "class-branch-divine-spark-and-ikons-secondIkon-level-1",
      "class-branch-divine-spark-and-ikons-thirdIkon-level-1",
      "class-branch-root-epithet-level-3",
    ],
    preferredSelections: {
      "class-branch-divine-spark-and-ikons-firstIkon-level-1": ["Eye-Catching Spot", "Gaze Sharp as Steel"],
      "class-branch-divine-spark-and-ikons-secondIkon-level-1": ["Scar of the Survivor", "Shadow Sheath"],
      "class-branch-divine-spark-and-ikons-thirdIkon-level-1": ["Skin Hard as Horn", "Gaze Sharp as Steel"],
      "class-branch-root-epithet-level-3": ["The Brave", "The Cunning"],
      "class-feat": ["Claim Initiate Domain", "Reactive Strike"],
    },
    preferredSkills: ["athletics", "diplomacy", "intimidation", "society", "acrobatics"],
  }),
  classCase({
    className: "Fighter",
    classSlug: "fighter",
    keyAbility: "str",
    expectedStepIds: ["class-choice-fighter-weapon-mastery-fighterWeaponMastery-level-5"],
    preferredSelections: {
      "class-feat": ["Reactive Shield", "Intimidating Strike", "Quick Reversal"],
      "skill-feat": ["Cat Fall", "Forager", "Acrobatic Performer", "Group Impression", "Quick Jump"],
    },
    preferredSkills: ["athletics", "acrobatics", "survival", "intimidation", "religion", "stealth"],
  }),
  {
    ...classCase({
      className: "Fighter",
      classSlug: "fighter",
      keyAbility: "str",
      expectedStepIds: [
        "class-choice-fighter-weapon-mastery-fighterWeaponMastery-level-5",
        "singleton-choice-feat-samsaran-weapon-memory-weaponOne-level-1",
        "singleton-choice-feat-samsaran-weapon-memory-weaponTwo-level-1",
      ],
      preferredSelections: {
        "ancestry-feat": ["Samsaran Weapon Memory"],
        "singleton-choice-feat-samsaran-weapon-memory-weaponOne-level-1": ["Longsword", "Falchion", "Glaive"],
        "singleton-choice-feat-samsaran-weapon-memory-weaponTwo-level-1": ["Longbow", "Composite Longbow", "Shortbow"],
        "class-feat": ["Reactive Shield", "Intimidating Strike", "Quick Reversal"],
      },
      preferredSkills: ["athletics", "acrobatics", "survival", "intimidation", "religion", "stealth"],
    }),
    id: "fighter-samsaran-weapon-memory-l1-l5-apply-rerun",
    label: "Fighter with Samsaran Weapon Memory config-feat level 1 through 5 apply/rerun",
    ancestryName: "Samsaran",
    heritageName: "Oracular Samsaran",
    ancestryBoosts: { "0": "con", "1": "wis", "2": "str" },
  },
  classCase({
    className: "Guardian",
    classSlug: "guardian",
    keyAbility: "str",
    preferredSelections: {
      "class-feat": ["Intercept Foe", "Armored Counterattack"],
    },
    preferredSkills: ["athletics", "intimidation", "medicine", "society", "survival"],
  }),
  classCase({
    className: "Gunslinger",
    classSlug: "gunslinger",
    keyAbility: "dex",
    expectedStepIds: ["class-branch-gunslingers-way-level-1"],
    preferredSelections: {
      "class-branch-gunslingers-way-level-1": ["Way of the Pistolero", "Way of the Sniper"],
      "class-feat": ["Cover Fire", "Hit the Dirt!"],
    },
    preferredSkills: ["acrobatics", "crafting", "deception", "intimidation", "stealth", "survival"],
  }),
  classCase({
    className: "Inventor",
    classSlug: "inventor",
    keyAbility: "int",
    expectedStepIds: ["class-choice-armor-innovation-armorInnovation-level-1", "class-branch-innovation-level-1"],
    preferredSelections: {
      "class-branch-innovation-level-1": ["Armor Innovation", "Weapon Innovation"],
      "class-feat": ["Built-In Tools", "Haphazard Repair"],
    },
    preferredSkills: ["crafting", "arcana", "athletics", "society", "thievery"],
  }),
  classCase({
    className: "Investigator",
    classSlug: "investigator",
    keyAbility: "int",
    expectedStepIds: ["class-branch-methodology-level-1"],
    preferredSelections: {
      "class-branch-methodology-level-1": [
        "Interrogation Methodology",
        "Forensic Medicine Methodology",
        "Empiricism Methodology",
      ],
      "class-feat": ["Known Weaknesses", "Flexible Studies", "Scalpel's Point"],
      "skill-feat": ["Cat Fall", "Forager", "Experienced Smuggler", "Acrobatic Performer", "Group Impression"],
    },
    preferredSkills: ["society", "arcana", "crafting", "medicine", "diplomacy", "stealth", "thievery", "deception"],
  }),
  classCase({
    className: "Kineticist",
    classSlug: "kineticist",
    keyAbility: "con",
    expectedStepIds: [
      "class-choice-kinetic-gate-kineticGate-level-1",
      "class-branch-kinetic-gate-elementOne-level-1",
      "class-branch-kinetic-gate-elementTwo-level-1",
      "class-choice-gates-threshold-gatesThreshold-level-5",
      "class-branch-gates-threshold-elementFork-level-5",
    ],
    preferredSelections: {
      "class-choice-kinetic-gate-kineticGate-level-1": ["dual-gate"],
      "class-branch-kinetic-gate-elementOne-level-1": ["Fire Gate", "Earth Gate"],
      "class-branch-kinetic-gate-elementTwo-level-1": ["Air Gate", "Water Gate"],
      "class-choice-gates-threshold-gatesThreshold-level-5": ["Fork the Path", "fork", "expand"],
      "class-branch-gates-threshold-elementFork-level-5": ["Wood Gate", "Earth Gate"],
      "class-choice-gate-s-threshold-gateSThreshold-level-5": ["Fork the Path", "fork", "expand"],
      "class-branch-gate-s-threshold-elementFork-level-5": ["Wood Gate", "Earth Gate"],
      "class-feat": ["Flying Flame", "Armor in Earth"],
    },
    preferredSkills: ["nature", "athletics", "crafting", "medicine", "survival"],
  }),
  classCase({
    className: "Magus",
    classSlug: "magus",
    keyAbility: "str",
    expectedStepIds: [
      "class-branch-hybrid-study-level-1",
      "spell-choice-magus-cantrips-level-1",
      "spell-choice-magus-spellbook-rank-1-level-1",
      "spell-choice-magus-spellbook-level-2",
      "spell-choice-magus-spellbook-level-3",
      "spell-choice-magus-spellbook-level-4",
      "spell-choice-magus-spellbook-level-5",
    ],
    preferredSelections: {
      "class-branch-hybrid-study-level-1": ["Inexorable Iron", "Sparkling Targe"],
      "class-feat": ["Force Fang", "Cantrip Expansion"],
    },
    preferredSkills: ["arcana", "athletics", "crafting", "society", "acrobatics"],
  }),
  classCase({
    className: "Monk",
    classSlug: "monk",
    keyAbility: "str",
    preferredSelections: {
      "class-feat": ["Crane Stance", "Stunning Blows"],
    },
    preferredSkills: ["acrobatics", "athletics", "medicine", "religion", "stealth"],
  }),
  classCase({
    className: "Oracle",
    classSlug: "oracle",
    keyAbility: "cha",
    expectedStepIds: [
      "class-branch-mystery-level-1",
      "spell-choice-oracle-cantrips-level-1",
      "spell-choice-oracle-repertoire-rank-1-level-1",
      "spell-choice-oracle-repertoire-rank-1-level-2",
      "spell-choice-oracle-repertoire-rank-2-level-3",
      "spell-choice-oracle-repertoire-rank-2-level-4",
      "spell-choice-oracle-repertoire-rank-3-level-5",
    ],
    preferredSelections: {
      "class-branch-mystery-level-1": ["Life", "Flames"],
      "class-feat": ["Reach Spell", "Divine Access"],
    },
    preferredSkills: ["religion", "diplomacy", "medicine", "occultism", "society"],
  }),
  classCase({
    className: "Psychic",
    classSlug: "psychic",
    keyAbility: "int",
    expectedStepIds: [
      "class-branch-conscious-mind-level-1",
      "class-branch-subconscious-mind-level-1",
      "spell-choice-psychic-cantrips-level-1",
      "spell-choice-psychic-repertoire-rank-1-level-1",
      "spell-choice-psychic-repertoire-rank-1-level-2",
      "spell-choice-psychic-repertoire-rank-2-level-3",
      "spell-choice-psychic-repertoire-rank-2-level-4",
      "spell-choice-psychic-repertoire-rank-3-level-5",
    ],
    preferredSelections: {
      "class-branch-conscious-mind-level-1": ["The Distant Grasp", "The Infinite Eye"],
      "class-branch-subconscious-mind-level-1": ["Gathered Lore", "Precise Discipline"],
      "class-feat": ["Counter Thought", "Cantrip Expansion"],
    },
    preferredSkills: ["occultism", "arcana", "society", "diplomacy", "medicine"],
  }),
  classCase({
    className: "Ranger",
    classSlug: "ranger",
    keyAbility: "dex",
    expectedStepIds: ["class-branch-hunters-edge-level-1"],
    preferredSelections: {
      "class-branch-hunters-edge-level-1": ["Precision", "Flurry"],
      "class-feat": ["Monster Hunter", "Twin Takedown"],
    },
    preferredSkills: ["survival", "nature", "acrobatics", "athletics", "stealth", "medicine"],
  }),
  classCase({
    className: "Rogue",
    classSlug: "rogue",
    keyAbility: "dex",
    expectedStepIds: ["class-branch-rogues-racket-level-1"],
    preferredSelections: {
      "class-branch-rogues-racket-level-1": ["Thief", "Scoundrel"],
      "class-feat": ["Nimble Dodge", "Trap Finder"],
      "skill-feat": ["Experienced Smuggler", "Cat Fall", "Forager", "Acrobatic Performer", "Group Impression"],
    },
    preferredSkills: ["stealth", "thievery", "acrobatics", "deception", "diplomacy", "society", "athletics", "survival"],
  }),
  classCase({
    className: "Sorcerer",
    classSlug: "sorcerer",
    keyAbility: "cha",
    expectedStepIds: [
      "class-branch-bloodline-level-1",
      "spell-choice-sorcerer-cantrips-level-1",
      "spell-choice-sorcerer-repertoire-rank-1-level-1",
      "spell-choice-sorcerer-repertoire-rank-1-level-2",
      "spell-choice-sorcerer-repertoire-rank-2-level-3",
      "spell-choice-sorcerer-repertoire-rank-2-level-4",
      "spell-choice-sorcerer-repertoire-rank-3-level-5",
    ],
    preferredSelections: {
      "class-branch-bloodline-level-1": ["Bloodline: Imperial", "Bloodline: Draconic"],
      "class-feat": ["Dangerous Sorcery", "Reach Spell", "Cantrip Expansion"],
      "skill-feat": ["Group Impression", "Cat Fall", "Forager", "Acrobatic Performer"],
    },
    preferredSkills: ["arcana", "deception", "diplomacy", "intimidation", "society", "religion", "stealth"],
  }),
  classCase({
    className: "Summoner",
    classSlug: "summoner",
    keyAbility: "cha",
    expectedStepIds: [
      "class-branch-eidolon-level-1",
      "class-branch-evolution-feat-level-1",
      "spell-choice-summoner-cantrips-level-1",
      "spell-choice-summoner-repertoire-rank-1-level-1",
      "spell-choice-summoner-repertoire-rank-1-level-2",
      "spell-choice-summoner-repertoire-rank-2-level-3",
      "spell-choice-summoner-repertoire-rank-2-level-4",
      "spell-choice-summoner-repertoire-rank-3-level-5",
    ],
    preferredSelections: {
      "class-branch-eidolon-level-1": ["Dragon Eidolon", "Angel Eidolon"],
      "class-branch-evolution-feat-level-1": ["Advanced Weaponry", "Energy Heart"],
      "class-feat": ["Reinforce Eidolon", "Lifelink Surge", "Skilled Partner"],
    },
    preferredSkills: ["arcana", "nature", "occultism", "religion", "diplomacy", "society"],
  }),
  classCase({
    className: "Swashbuckler",
    classSlug: "swashbuckler",
    keyAbility: "dex",
    expectedStepIds: ["class-branch-swashbucklers-style-level-1"],
    preferredSelections: {
      "class-branch-swashbucklers-style-level-1": ["Fencer", "Wit"],
      "class-feat": ["One for All", "Flying Blade"],
    },
    preferredSkills: ["acrobatics", "athletics", "diplomacy", "deception", "intimidation", "performance"],
  }),
  classCase({
    className: "Thaumaturge",
    classSlug: "thaumaturge",
    keyAbility: "cha",
    expectedStepIds: [
      "class-choice-initiate-benefit-wand-initiateBenefitWand-level-1",
      "class-branch-first-implement-and-esoterica-level-1",
      "class-branch-second-implement-level-5",
    ],
    preferredSelections: {
      "class-branch-first-implement-and-esoterica-level-1": ["Amulet", "Weapon"],
      "class-branch-second-implement-level-5": ["Wand", "Tome"],
      "class-feat": ["Diverse Lore", "Scroll Thaumaturgy"],
    },
    preferredSkills: ["esoteric-lore", "arcana", "occultism", "religion", "society", "diplomacy"],
  }),
  classCase({
    className: "Witch",
    classSlug: "witch",
    keyAbility: "int",
    expectedStepIds: [
      "class-branch-patron-level-1",
      "spell-choice-witch-cantrips-level-1",
      "spell-choice-witch-rank-1-level-1",
    ],
    preferredSelections: {
      "class-branch-patron-level-1": ["Spinner of Threads", "Faith's Flamekeeper"],
      "class-feat": ["Cackle", "Widen Spell"],
    },
    preferredSkills: ["occultism", "arcana", "nature", "religion", "crafting", "society"],
  }),
  classCase({
    className: "Wizard",
    classSlug: "wizard",
    keyAbility: "int",
    expectedStepIds: [
      "class-branch-arcane-school-level-1",
      "class-branch-arcane-thesis-level-1",
      "spell-choice-wizard-curriculum-rank-1-level-1",
      "spell-choice-wizard-spellbook-cantrips-level-1",
      "spell-choice-wizard-spellbook-rank-1-level-1",
      "spell-choice-wizard-spellbook-level-2",
      "spell-choice-wizard-curriculum-rank-2-level-3",
      "spell-choice-wizard-spellbook-level-3",
      "spell-choice-wizard-spellbook-level-4",
      "spell-choice-wizard-curriculum-rank-3-level-5",
      "spell-choice-wizard-spellbook-level-5",
    ],
    preferredSelections: {
      "class-feat": ["Reach Spell", "Counterspell", "Cantrip Expansion"],
      "skill-feat": ["Recognize Spell", "Cat Fall", "Forager", "Acrobatic Performer"],
    },
    preferredSkills: ["arcana", "crafting", "society", "occultism", "religion", "medicine", "nature"],
  }),
];
